import { SpeedInsights } from "@vercel/speed-insights/next";
import { Mulish } from "next/font/google";
import "./globals.css";

const mulish = Mulish({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-Mulish",
});

export const metadata = {
  title: {
    default: "Linker",
    template: "%s | Linker",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true} data-theme="lightTheme">
      <body className={`${mulish.variable}`} suppressHydrationWarning={true}>
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
